# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abemerica's Foray Into Programming
email: aberanderson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog where I talk about trying to be a programmer and how either awesome or embarssing that ends up being. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://americool.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  americool

# Build settings
markdown: kramdown
